global:
  env: dev

flaskApp:
  replicaCount: 1
  image:
    tag: 1.1.0
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

mysql:
  persistence:
    enabled: true