global:
  env: dev
  appName: flask-mysql-app

flaskApp:
  image:
    repository: hm25-flask-app
    tag: latest
    pullPolicy: Never
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    FLASK_ENV: development
    PORT: 5000
    MYSQL_HOST: "{{ .Release.Name }}-mysql"

mysql:
  enabled: true
  image:
    repository: mysql
    tag: 8.0
    pullPolicy: IfNotPresent
  rootPassword: "rootpass"
  database: "flaskdb"
  username: "flaskuser"
  password: "flaskpass"
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: nginx.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []