global:
  env: prod

flaskApp:
  replicaCount: 2
  image:
    tag: 1.0.0
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

mysql:
  persistence:
    enabled: true
    size: 2Gi