{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-mysql-app.mysql.fullname" . }}
  labels:
    app: {{ include "flask-mysql-app.fullname" . }}
    component: mysql
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
{{- end }}